pull_request_rules:
  - name: Automatic merge PR by dependabot
    conditions:
      - "author=dependabot[bot]"
      - "status-success=build (ubuntu-latest)"
    actions:
      merge:
        method: merge
      delete_head_branch: 
        force: true
