name: "release-downloader"
description: "Download release assets from private or public github repositories"
author: "Robin Raju"
inputs:
  repo-path:
    description: "The source repository path. Expected format {owner}/{repo}"
    default: ""
    required: true
  latest:
    description: "A flag to choose between latest release and remaining releases"
    default: "true"
    required: false
  out-file-path:
    description: "Relative path under $GITHUB_WORKSPACE to place the downloaded file"
    default: "."
    required: true
  token:
    description: "Github token to access private repos"
    default: ""
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
